# Generated by Django 4.1 on 2024-06-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='punejobs',
            name='address',
        ),
        migrations.AlterField(
            model_name='bngjobs',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hydjobs',
            name='address',
            field=models.TextField(),
        ),
    ]
